### ISSUE TITLE
No way to use UIViewControllerBasedStatusBarAppearance

### ISSUE THREAD

**Issue by michallaskowski** [Crownpeak/AppNoticeSDK-iOS#10]
Hi,
in our apps we are trying to move away from a deprecated API to set status bar style/visibility on UIApplication instance, and use instead UIViewControllerBasedStatusBarAppearance. Which is also better for many other reasons.
It seems there is no way to use this approach with AppNoticeSDK for Preference Manager screen. There is no pointer to the presented navigation controller. Even if there was, we need to have control over the properties that are read only, like `preferredStatusBarStyle`.

Easy way to solve it would be ability to pass an instance of `UINavigationController`, this could be added without breaking compatibility, by keeping the older method and creating navigationController if client does not pass it.
```
- (void)showManagePreferences:(AppNoticeSDKPreferencesClosedBlock)onClose presentingViewController:(UIViewController*)vc; // this is the current declaration

- (void)showManagePreferences:(AppNoticeSDKPreferencesClosedBlock)onClose presentingViewController:(UIViewController*)vc using:(UINavigationController *)navigationController; // need to add this one
```
This way an app can create its own subclass of UINavigationController, which can set `preferredStatusBarStyle` accordingly, and pass it to AppNoticeSDK.

**Comment by jdowd7** [comment]
Hi @michallaskowski, thanks for the explanation. I believe we can implement your proposed solution, investigating if there are any breaking changes on our end and I will get back to you asap.

**Comment by michallaskowski** [comment]
Awesome, thanks. This is probably one of many solutions, but one I believe keeps backward compatibility and one of the easiest to do.

**Comment by jdowd7** [comment]
@michallaskowski I have a prototype SDK for you to test- will have PM reach out and so we can figure out a way to transfer the test framework.

**Comment by jdowd7** [comment]
Hey @michallaskowski good speaking with you, per our convo, check out #11  for that SDK.

**Comment by jdowd7** [comment]
@michallaskowski did it address your issue? 
Lmk and I can integrate it into a release (for cocoapods, not carthage yet, apologies)

**Comment by michallaskowski** [comment]
Hey, thanks a lot for a quick SDK change. I tested this out and worked out fine, I was able to change status bar style. It seems at least navBarTitleColor is no longer applied. But I am fine with that if this means I can style the status bar.

Had to use use this:

```
final class StyledNavigationController: UINavigationController {

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }

    override var prefersStatusBarHidden: Bool {
        return false
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationBar.backgroundColor = Configuration.Colors.AppNoticeNavBarBackground.color()
        navigationBar.tintColor = Configuration.Colors.AppNoticeNavBarTitle.color()
        navigationBar.titleTextAttributes = [.foregroundColor: Configuration.Colors.AppNoticeNavBarTitle.color()]
    }
}
```

**Comment by jdowd7** [comment]
I can create an issue and check into that, but atm won't consider it as a blocker for this SDK release. Thanks @michallaskowski

**Comment by michallaskowski** [comment]
Ok, thanks. Should I continue with the SDK that is included in the PR, or should I wait for a new release on master branch?

**Comment by jdowd7** [comment]
@michallaskowski you can use that binary- it'll be the same thing, just waiting on something before issuing a new cocoapods release

**Comment by jdowd7** [comment]
merged in, will push new cocoapods release shortly
