### ISSUE TITLE
Bitcode builds not supported

### ISSUE THREAD

**Issue by xfreebird** [Crownpeak/AppNoticeSDK-iOS#13]
Hi,

Is there any roadmap to provide bitcode enabled builds?

Thanks!

```
❌  ld: bitcode bundle could not be generated because '/Users/jenkins/build/workspace/project/Pods/AppNotice/AppNotice/AppNoticeSDKFramework.framework/AppNoticeSDKFramework(PreferencesDetailViewController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/jenkins/build/workspace/project/Pods/AppNotice/AppNotice/AppNoticeSDKFramework.framework/AppNoticeSDKFramework' for architecture armv7
```

**Comment by walsht** [comment]
@jdowd7 When can we see this update?  This is blocking our implementation. Been around since XCode 7, should be a quick update.

**Comment by jdowd7** [comment]
@walsht Try this build out
[AppNoticeSDKFramework_archiveBitcode.zip](https://github.com/Crownpeak/AppNoticeSDK-iOS/files/2602018/AppNoticeSDKFramework_archiveBitcode.zip)

**Comment by walsht** [comment]
@jdowd7 This works perfectly, do you mind putting it as a version on GitHub?  We use Carthage, so the new version will help.

Thank you,
Tim
