### ISSUE TITLE
localization-and-text-customization not working

### ISSUE THREAD

**Issue by walsht** [Crownpeak/AppNoticeSDK-iOS#14]
I tried to implement these [steps](https://github.com/Crownpeak/AppNoticeSDK-iOS#localization-and-text-customization), but updated localization for these values are not being picked up.
"ghostery_manage_preferences_explicit_accept_button" = "Accept";
"ghostery_manage_preferences_button" = "Manage Settings";

**Comment by walsht** [comment]
@jdowd7 Can you comment on this ticket?

**Comment by jdowd7** [comment]
I have 'manage settings overriding 'manage preferences' as expected:
OG:
![image](https://user-images.githubusercontent.com/2521560/47870950-57c0f680-ddd0-11e8-8d11-54917fe29f88.png)
Overridden:
![image](https://user-images.githubusercontent.com/2521560/47870781-01ec4e80-ddd0-11e8-9881-3aad4a9926e8.png)

If you are looking to override the notification accept wording then the below is incorrect one: "ghostery_manage_preferences_explicit_accept_button" = "Accept";

Use this key instead:
"ghostery_dialog_button_explicit_consent" = "Accept";

**Comment by walsht** [comment]
Thank you.
