### ISSUE TITLE
AppNotice to App-Notice migration

### ISSUE THREAD

**Issue by xfreebird** [Crownpeak/AppNoticeSDK-iOS#17]
Hi,

I noticed that the pod name was changed, is it safe to upgrade to start using App-Notice instead of AppNotice pod?
Currently we are using latest AppNotice pod 2.2.0, is the upgrade to App-Notice straight forward? is there any guide?

Thanks,
Nicolae

**Comment by jdowd7** [comment]
@xfreebird apologies for the delay- yes, you can upgrade if you prefer.
The App-Notice pod is the GDPR compliant version. There is also an App-Notice IAB compliant version.
Implementation is pretty much the same with a few changes, mainly you can enforce GDPR based on countries of your choosing.
Drop us an email at Evidon if you have trouble.

**Comment by jdowd7** [comment]
@xfreebird best place to start is on the header file for the SDK:
[header file](https://github.com/Crownpeak/AppNoticeSDK-iOS/blob/master/AppNotice/AppNoticeSDKFramework.framework/Versions/A/Headers/AppNoticeSDK.h)

**Comment by xfreebird** [comment]
@jdowd7 it would be great to have that in github release notes that explains all changes.

**Comment by jdowd7** [comment]
@xfreebird apologies about that. Will try and get more updated docs out soon!
