### ISSUE TITLE
AppNoticeSDK-iOS 2.4.3 - consents are not persisted after subsequent app launch

### ISSUE THREAD

**Issue by GBartek** [Crownpeak/AppNoticeSDK-iOS#20]
Hi AppNoticeSDK-iOS Team,

It seems that consents are not persisted so after subsequent app launch an empty list is displayed.

**Environment**
* AppNoticeSDK 2.4.3 is used
* As soon as application becomes active and all UI stuff is done the following code is executed:
```swift
AppNoticeSDK.sharedInstance().showExplicitConsentFlowWith(onClose: { (result, trackers) in
/// ...
```
* There is some kind of "Settings" option to allow user to see consent for individual trackers. The following code is executed:
```swift
AppNoticeSDK.sharedInstance().showManagePreferences( { ...
```
* There is UI customization set on navigation bar to use custom color - for example:
```swift
AppNoticeSDK.sharedInstance().navBarTitleColor = .white
```

**Steps to reproduce:**

* Install an app on a simulator/device
* As soon as action sheet becomes visible click "Manage Preferences" 
* On newly presented screen click "Optional Technologies" check button and then press "Done" button placed in the upper-right corner. See screenshot below for reference:

![screenshot-1](https://user-images.githubusercontent.com/5587735/52918808-9b962800-32fb-11e9-9bf5-02fd76a080b2.png)

* Kill the app and launch again
* Go to "Settings" option (see **Environment** section) so `AppNoticeSDK` code will be explicitly called.

**Actual result:** 
There are no consents list on "Privacy Preferences" screen. In addition it seems that `AppNoticeSDK.navBarTitleColor` is not respected in that case. See screenshot below:

![screenshot-2](https://user-images.githubusercontent.com/5587735/52918935-288db100-32fd-11e9-9824-4ecb2a8de69e.png)

One note: When playing with **Triangle_swift** sample it's also possible to achieve the same result (an empty consents list) but with a little bit different scenario.

**Comment by GBartek** [comment]
PS. After subsequent app launch and `AppNoticeSDK.isLogEnabled` set to `true` there are some information about trackers, maybe it will be helpful:

```
**MASTER AppState Loaded with Tracker Count == 5
// List of consents with values (0 or 1)

**AppState Loaded with Tracker Count == 5
// List of consents with values (0 or 1)

No Persisted Categories Exists
```

**Comment by jdowd7** [comment]
@GBartek thanks for the report.
Reupping the framework soon with fix.

**Comment by jdowd7** [comment]
@GBartek will let you know here when new version is up

**Comment by GBartek** [comment]
Cool! Thanks @jdowd7 for your quick response and the update!
