### ISSUE TITLE
AppNoticeSDK-iOS 2.4.5 - App crash after launch

### ISSUE THREAD

**Issue by GBartek** [Crownpeak/AppNoticeSDK-iOS#21]
Hi AppNoticeSDK-iOS Team,

It seems that application crashes after **2.4.5** update. The steps to reproduce is quite simple - I've just replaced **AppNoticeSDKFramework.framework** with new version available in release tab here: https://github.com/Crownpeak/AppNoticeSDK-iOS/releases

In the end I'm finishing up with uncaught exception with details as below:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object null for key lastVersion'

One thing to notice: I've performed a clean install (so I've deleted previously installed app, also cleaning build folder was performed). I've also set `isLogEnabled` to `true`.

After setting "All Exceptions" breakpoint stack trace looks as below (we can ignore `_NRMAOverride_` because it seems one of the method instrumented by `NewRelic` is called):

![screen2](https://user-images.githubusercontent.com/5587735/53415594-f0a7fd00-39d1-11e9-8548-feffef8ea79f.png)

After investigating the content in rows 14, 13, 12 I encountered a few methods names - maybe it will help you to find what causes an issue. I've cleared it up a little bit so here's the output - hope it contains some flow:

```swift
    // Some hard-to-read content ...
    0x10ce4d143 <+68>:  movq   0x3aaafe(%rip), %rsi      ; "statusCode"
    // ...
    0x10ce4d15a <+91>:  movq   0x3b4fd7(%rip), %rdi      ; (void *)0x000000010d215878: AppNoticeSDK
    0x10ce4d161 <+98>:  movq   0x3a9c60(%rip), %rsi      ; "sharedInstance"
    // ...
    0x10ce4d176 <+119>: movq   0x3aaa8b(%rip), %r12      ; "isLogEnabled"
    // ...
    0x10ce4d197 <+152>: leaq   0x2f1582(%rip), %rdi      ; @"\n\n*** httpResponse: %@"
    // ...
    0x10ce4d1a8 <+169>: leaq   0x2f1591(%rip), %rdi      ; @"\n\n***\n\nstatusCode == %ld\n\n" 
    // ...
    0x10ce4d229 <+298>: movq   0x3aaa98(%rip), %rsi      ; "absoluteString"
    // ...
    0x10ce4d240 <+321>: movq   0x3aaa89(%rip), %rsi      ; "localizedDescription"
    // ...
    0x10ce4d258 <+345>: leaq   0x2f15c1(%rip), %rdi      ; @"Error calling %@: %@"
    // ...
    0x10ce4d349 <+586>: leaq   0x2f14f0(%rip), %rdi      ; @"JSON Error Encountered"
    // ...
    0x10ce4d35c <+605>: movq   0x3aa975(%rip), %rsi      ; "setOriginalJSONDictionary:"
    // ...
    0x10ce4d37e <+639>: movq   0x3aa95b(%rip), %rsi      ; "loadDataFromDictionary:"
    // ...
    0x10ce4d39c <+669>: movq   0x3b4ff5(%rip), %rdi      ; (void *)0x000000010d2154b8: ConsentDataStore
    0x10ce4d3a3 <+676>: movq   0x3a9a1e(%rip), %rax      ; "sharedInstance"
    // ...
    0x10ce4d3bd <+702>: movq   0x3aa62c(%rip), %rsi      ; "initializeWithArray:"
    // ...
    0x10ce4d3d6 <+727>: movq   0x3aa62b(%rip), %rsi      ; "tokenVersion"
    // ...
    0x10ce4d3ef <+752>: movq   0x3b4fa2(%rip), %rdi      ; (void *)0x000000010d2154b8: ConsentDataStore
    // ...
    0x10ce4d40b <+780>: movq   0x3aa5e6(%rip), %rsi      ; "setLastVersion:"
    // ...
    0x10ce4d430 <+817>: movq   0x3aacd9(%rip), %rsi      ; "saveAppState"
``` 

If you take a look at stack trace above there are some errors like `@"Error calling %@: %@"` - hope it helps.

**Comment by jdowd7** [comment]
@GBartek have a new version to be released soon, should address the issue.
Is it still happening for you after uninstalling and reinstalling?

**Comment by GBartek** [comment]
@jdowd7 I was able to reproduce it after uninstalling and reinstalling (AFAIK it was regular scenario), currently I'm using an older version of AppNoticeSDK which doesn't crash at launch. Cool that new version will address the issue! Hope to see it soon 👍

**Comment by jdowd7** [comment]
@GBartek new version released

**Comment by GBartek** [comment]
Hi @jdowd7 

After update I'm getting the similar error, but with a little bit different description:

> Attempt to set a non-property-list object <null> as an NSUserDefaults/CFPreferences value for key appNoticeLastVersion

I've removed my app completely from iOS simulator and after new binaries upload I've build the app again (with cleaning the build folder before). The stack trace looks very similar as in my first comment. Is that information enough to you or should I perform some more advanced investigation ?

**Comment by jdowd7** [comment]
Hey @GBartek,

Had someone run into this the other day actually- due to the refresh feature we added.
You will need to make sure you have a version number set in the appNotice UI:

![image](https://user-images.githubusercontent.com/2521560/55414752-fa6cd500-5528-11e9-8710-a1da4cbb0f7e.png)

Let me know if that works for you.
Thanks

**Comment by GBartek** [comment]
Thanks @jdowd7 

I did some tests and it seems that it works as expected. It was tested with Versions set to **1** - just like in attachment above. Just one question out of curiosity - what purpose is the "Versions" parameter used for ? Will it have any impact for current live apps (note that currently I'm using an older version of **AppNoticeSDK**) ? I'm asking because I'm wondering if it causes an issue for live apps.

**Comment by jdowd7** [comment]
@GBartek 

It shouldn't have any impact on the live apps, the SDK wasn't using this value before.

Its utilized for the app to determine the token version. But version is just a string, if you make a change to your setup please change the version number.

Thanks!
